#Conda dependencies
name: python-example

channels:
  - conda-forge

dependencies:
  #List here all the conda-dependant dependencies of your project
  - python>=3.6
  - pip
  #Add conda-available pip-dependencies when available. Conda's dependency
  #management works better. (`conda search [package]` to find out)
  - setuptools
  #For tests
  - pytest>=3
  - pytest-cov
