#Conda dependencies
name: python-example

channels:
  - conda-forge

dependencies:
  #List here all the conda-dependant dependencies of your project
  - python>=3.6
  #For tests
  - pytest>=3
  - pytest-cov
  #For your code to run
  - setuptools
  - pip
