#Conda dependencies
name: python-example

channels:
  - conda-forge

dependencies:
  #List here all the conda-dependant dependencies of your project
  - python=3.7
  - pip=19.1
  #Add conda-available pip-dependencies when available. Conda's dependency
  #management works better. (`conda search [package]` to find out)
  - setuptools=41.0
  #For tests
  - pytest=4.4
  - pytest-cov=2.7
